version: '3.8'

services:
  socks5balancer:
    image: fossforreal/socks5balancerasio:latest-amd64
    container_name: socks5_balancer
    ports:
      - "1080:1080"
    volumes:
      - ./config.json:/config.json:ro
    restart: unless-stopped
    command: /Socks5BalancerAsio/Socks5BalancerAsio config.json
