version: '3.8'

services:
  socks5balancer:
    image: fossforreal/socks5balancerasio-docker
    container_name: socks5_balancer
    ports:
      - "${BALANCER_PORT}:1080/tcp"
      - "${STATE_SERVER_PORT}:8080/tcp"
    volumes:
      - ./config.json:/Socks5BalancerAsio/config.json:ro
    restart: unless-stopped
    networks:
      - proxy-network

networks:
  proxy-network:
    driver: bridge