version: '3.8'

services:
  socks5balancer:
    image: fossforreal/socks5balancerasio:latest-amd64
    container_name: socks5_balancer
    ports:
      - "${BALANCER_PORT:-1080}:1080/tcp"
      - "${STATE_SERVER_PORT:-8080}:8080/tcp"
    volumes:
      - ./config.json:/config.json:ro  # смонтировать прямо в /config.json
    restart: unless-stopped
    networks:
      - proxy-network
    command: /Socks5BalancerAsio/Socks5BalancerAsio config.json  # путь БЕЗ слеша

networks:
  proxy-network:
    driver: bridge
