version: '3.8'

services:
  dante:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dante_proxy
    ports:
      - "${SOCKS_PORT:-1080}:1080"
    volumes:
      - ./danted.conf.template:/etc/danted.conf.template
      - ./entrypoint.sh:/entrypoint.sh
    environment:
      - TZ=UTC
      - SOCKS_PORT=${SOCKS_PORT:-1080}
      - USER=${USER:-proxyuser}
      - PASS=${PASS:-proxypass}
    restart: unless-stopped
    networks:
      - proxy_network
    command: /entrypoint.sh

networks:
  proxy_network:
    driver: bridge
