version: '3.8'

services:
  dante:
    image: vimagick/dante:latest
    container_name: dante_proxy
    ports:
      - "${SOCKS_PORT}:1080/tcp"
    volumes:
      - ./danted.conf:/etc/danted.conf:ro
      - ./entrypoint.sh:/entrypoint.sh:ro
    environment:
      - SOCKS_USER=${SOCKS_USER}
      - SOCKS_PASS=${SOCKS_PASS}
    entrypoint: ["/entrypoint.sh"]
    restart: unless-stopped
    networks:
      - proxy-network

networks:
  proxy-network:
    driver: bridge