version: '3.8'

services:
  squid:
    build: ./squid
    ports:
      - "${HTTP_PORT:-3128}:3128"
    volumes:
      - ./squid/squid.conf:/etc/squid/squid.conf
      - ./credentials/squid.passwd:/etc/squid/passwd
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "squidclient", "-h", "localhost", "cache_object://localhost/counters"]
      interval: 30s
      timeout: 10s
      retries: 3
    env_file:
      - ../.env

  dante:
    build: ./dante
    ports:
      - "${SOCKS_PORT:-1080}:1080"
    volumes:
      - ./dante/sockd.conf:/etc/sockd.conf
      - ./credentials/dante.passwd:/etc/dante/passwd
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "1080"]
      interval: 30s
      timeout: 10s
      retries: 3
    env_file:
      - ../.env 
