version: "3.8"

services:
  squid:
    image: ubuntu/squid:latest
    container_name: squid_proxy
    ports:
      - "${HTTP_PORT:-3128}:3128"
    volumes:
      - ./squid.conf:/etc/squid/squid.conf
      - ./credentials/squid.passwd:/etc/squid/passwd:ro
      - ./cache:/var/cache/squid
    environment:
      - TZ=UTC
    restart: unless-stopped
    networks:
      - proxy_network
    healthcheck:
      test: ["CMD", "squidclient", "-h", "localhost", "cache_object://localhost/counters"]
      interval: 30s
      timeout: 10s
      retries: 3
    env_file:
      - ../.env

  dante:
    image: vimagick/dante:latest
    container_name: dante_proxy
    ports:
      - "${SOCKS_PORT:-1080}:1080"
    volumes:
      - ./sockd.conf:/etc/sockd.conf
      - ./credentials/dante.passwd:/etc/dante.passwd:ro
    environment:
      - TZ=UTC
    restart: unless-stopped
    networks:
      - proxy_network
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "1080"]
      interval: 30s
      timeout: 10s
      retries: 3
    env_file:
      - ../.env

networks:
  proxy_network:
    driver: bridge
